name: Continous Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      terraform_status: apply

      TF_VAR_MAC_UE_TENANT_HUB_PROD_SUB_client_id: ${{ secrets.MAC_UE_TENANT_HUB_PROD_SUB_client_id }}
      TF_VAR_MAC_UE_TENANT_HUB_PROD_SUB_client_secret: ${{ secrets.MAC_UE_TENANT_HUB_PROD_SUB_client_secret }}
      TF_VAR_MAC_UE_TENANT_HUB_PROD_SUB_subscription_id: ${{ secrets.MAC_UE_TENANT_HUB_PROD_SUB_subscription_id }}
      TF_VAR_MAC_UE_TENANT_HUB_PROD_SUB_tenant_id: ${{ secrets.MAC_UE_TENANT_HUB_PROD_SUB_tenant_id }}

      TF_VAR_MAC_UE_TENANT_MY_APP_PROD_SUB_client_id: ${{ secrets.MAC_UE_TENANT_MY_APP_PROD_SUB_client_id }}
      TF_VAR_MAC_UE_TENANT_MY_APP_PROD_SUB_client_secret: ${{ secrets.MAC_UE_TENANT_MY_APP_PROD_SUB_client_secret }}
      TF_VAR_MAC_UE_TENANT_MY_APP_PROD_SUB_subscription_id: ${{ secrets.MAC_UE_TENANT_MY_APP_PROD_SUB_subscription_id }}
      TF_VAR_MAC_UE_TENANT_MY_APP_PROD_SUB_tenant_id: ${{ secrets.MAC_UE_TENANT_MY_APP_PROD_SUB_tenant_id }}  

      TF_VAR_MAC_UE_TENANT_MY_APP_TEST_SUB_client_id: ${{ secrets.MAC_UE_TENANT_MY_APP_TEST_SUB_client_id }}
      TF_VAR_MAC_UE_TENANT_MY_APP_TEST_SUB_client_secret: ${{ secrets.MAC_UE_TENANT_MY_APP_TEST_SUB_client_secret }} 
      TF_VAR_MAC_UE_TENANT_MY_APP_TEST_SUB_subscription_id: ${{ secrets.MAC_UE_TENANT_MY_APP_TEST_SUB_subscription_id }}
      TF_VAR_MAC_UE_TENANT_MY_APP_TEST_SUB_tenant_id: ${{ secrets.MAC_UE_TENANT_MY_APP_TEST_SUB_tenant_id }}    

      TF_VAR_MAC_UE_TENANT_MY_APP_DEV_SUB_client_id: ${{ secrets.MAC_UE_TENANT_MY_APP_DEV_SUB_client_id }}
      TF_VAR_MAC_UE_TENANT_MY_APP_DEV_SUB_client_secret: ${{ secrets.MAC_UE_TENANT_MY_APP_DEV_SUB_client_secret }}
      TF_VAR_MAC_UE_TENANT_MY_APP_DEV_SUB_subscription_id: ${{ secrets.MAC_UE_TENANT_MY_APP_DEV_SUB_subscription_id }}
      TF_VAR_MAC_UE_TENANT_MY_APP_DEV_SUB_tenant_id: ${{ secrets.MAC_UE_TENANT_MY_APP_DEV_SUB_tenant_id }} 

     steps:
      - name: Checkout
        uses: actions/checkout@v3       

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1 

      - name: Terraform Init
        working-directory: TF-MAC-HUB-SPOKE
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: TF-MAC-HUB-SPOKE
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        working-directory: TF-MAC-HUB-SPOKE
        id: validate
        run: terraform validate

      - name: Terraform Plan
        working-directory: TF-MAC-HUB-SPOKE
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        working-directory: TF-MAC-HUB-SPOKE
        if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        working-directory: TF-MAC-HUB-SPOKE
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.terraform_status == 'apply'
        run: terraform apply -auto-approve
        continue-on-error: true

      - name: Terraform Apply Status
        working-directory: TF-MAC-HUB-SPOKE
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.apply.outcome == 'failure' && env.terraform_status == 'apply'
        run:
          exit 1    

      - name: Terraform Destroy
        working-directory: TF-MAC-HUB-SPOKE
        id: destroy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.infrastructure_status == 'destroy'
        run: | 
          terraform destroy -auto-approve                               
